# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        rfbrowser init
    - name: Set Environment
      run: ./setenv.sh
    - name: Test with RobotFramework
      run: robot --variable browser:chromium --variable headless:True --variable url:https://test4.omenahotels.com/ --outputdir reports/ testsuites/
      continue-on-error: true
  copy-files:
    runs-on: ubuntu-latest
    needs: build
    steps:
          - uses: actions/checkout@v2
          - run: echo "Copying files to repository..."
          - uses: actions/upload-artifact@v2
            with:
              name: reports
              path: /home/runner/work/nelson-test-automation/nelson-test-automation/reports
