name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        rfbrowser init
    - name: Test with RobotFramework
      run: robot --exclude skip --variable browser:chromium --variable headless:True --variable url:https://test4.omenahotels.com/ --variable MUI-Link:https://admin.nelson.management/#/login --outputdir reports/ testsuites/ 
      continue-on-error: True
    - name: Commit files
      run: |
        echo "Commit reporting files"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add /home/runner/work/nelson-test-automation/nelson-test-automation/reports
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
      continue-on-error: True
    - name: Copy files to gh-pages branch
      uses: planetoftheweb/copy-to-branches@v1.2
      env:
          key: develop
          branches: gh-pages
          files: reports
      continue-on-error: True
    - name: Publish Reports to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
