name: Regression Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
        logLevel:
            description: 'Log level'
            required: false
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
        tags:
            description: 'Test scenario tags'
            required: false
            type: boolean
        environment:
            description: 'Environment to run tests against'
            type: environment
            required: false

env:
    TEST_ENV: "staging"
    MUI_PASSWORD: ${{ secrets.MUI_PASSWORD }}
    MUI_URL: ${{ secrets.MUI_URL }}
    MUI_USERNAME: ${{ secrets.MUI_USERNAME }}
    TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
    TEST_EMAIL_PASSWORD: ${{ secrets.TEST_EMAIL_PASSWORD }}
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
    GMAIL_ACCESS_TOKEN: ${{ secrets.GMAIL_ACCESS_TOKEN }}
    GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
    GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
    GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
    TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
permissions:
  write-all

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          rfbrowser init
          npm install -g @testmo/testmo-cli

      - name: Test Mailslurp
        run: python -s resources/libraries/MailSlurp.py
        continue-on-error: True 

      - name: Run Pre-Tests
        run: robot --argumentfile environments/pretest.txt --variable MUI_URL:${{ secrets.MUI_URL }} --variable MUI_USERNAME:${{ secrets.MUI_USERNAME }} --variable MUI_PASSWORD:${{ secrets.MUI_PASSWORD }} --variable MAILSLURP_API_KEY:${{ secrets.MAILSLURP_API_KEY }} --outputdir reports/pretest testsuites/pretest.robot
        continue-on-error: True 
    
      - name: Make the script executable
        run: chmod +x scripts/run_tests.sh

      - name: Run Tests on listed Environments
        run: ./scripts/run_regression.sh 
        continue-on-error: True 

      - name: Commit files
        run: |
          echo "Commit reporting files"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add /home/runner/work/nelson-test-automation/nelson-test-automation/reports
          git commit -a -m "Add changes"
        continue-on-error: True

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
        continue-on-error: True

      - name: Copy files to gh-pages branch
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          key: develop
          branches: gh-pages
          files: reports
        continue-on-error: True

      - name: Publish Reports to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
        continue-on-error: True
