name: Robot Framework Tests on Nelson

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  write-all

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set Environment Variables
        env:
          TEST_ENV: "staging"
          MUI_PASSWORD: ${{ secrets.MUI_PASSWORD }}
          MUI_URL: ${{ secrets.MUI_URL }}
          MUI_USERNAME: ${{ secrets.MUI_USERNAME }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_EMAIL_PASSWORD: ${{ secrets.TEST_EMAIL_PASSWORD }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
        run: echo "Environment variables set"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          rfbrowser init

      - name: Run Pre-Tests
        run: robot -A environments/pretest.txt --outputdir reports/pretest testsuites/pretest.robot

      - name: Test Omena Testing Environment test4
        run: robot -A environments/test4.txt --outputdir reports/test4 testsuites/
        continue-on-error: False

      - name: Test EC Testing Environment exhibition-test
        run: robot -A environments/ectest.txt --outputdir reports/ectest testsuites/
        continue-on-error: False

  report:
    needs: setup
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Commit files
        run: |
          echo "Commit reporting files"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add /home/runner/work/nelson-test-automation/nelson-test-automation/reports
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

      - name: Copy files to gh-pages branch
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          key: develop
          branches: gh-pages
          files: reports

      - name: Publish Reports to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
